# This workflow will build different GAMA release
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: GAMA Generator

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  workflow_dispatch:  # For manual trigger


jobs:
  
  # ---

  jdk17-HotSpot-SWT_2022-06:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'gama-platform/gama'
          ref: 'GAMA_1.8.2'
      
      - name: Set up Temurin 17
        uses: actions/setup-java@v2 
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk
          cache: 'maven'

      - name: Change SWT
        run: |
         # POM
         sed -i 's/releases\/2021-12/releases\/2022-06/g' $GITHUB_WORKSPACE/ummisco.gama.annotations/pom.xml
         sed -i 's/releases\/2021-12/releases\/2022-06/g' $GITHUB_WORKSPACE/msi.gama.processor/pom.xml
         sed -i 's/releases\/2021-12/releases\/2022-06/g' $GITHUB_WORKSPACE/msi.gama.parent/pom.xml
      
      - name: Build
        run: bash $GITHUB_WORKSPACE/travis/compile.sh
      
      - name: Zip
        run: bash $GITHUB_WORKSPACE/travis/zip_withjdk.sh
      
      - name: Test build headless
        run: bash $GITHUB_WORKSPACE/ummisco.gama.product/target/products/ummisco.gama.application.product/linux/gtk/x86_64/headless/gama-headless.sh -validate 
      
      - name: Prepare releases
        run: |
          mkdir $GITHUB_WORKSPACE/jdk17-HotSpot-SWT_2022-06
          mv $GITHUB_WORKSPACE/ummisco.gama.product/target/products/Gama1.7-linux.gtk.x86_64_withJDK.zip $GITHUB_WORKSPACE/jdk17-HotSpot-SWT_2022-06/Linux-jdk17-HotSpot-SWT_2022-06.zip
          mv $GITHUB_WORKSPACE/ummisco.gama.product/target/products/Gama1.7-win32.win32.x86_64_withJDK.zip $GITHUB_WORKSPACE/jdk17-HotSpot-SWT_2022-06/Windows-jdk17-HotSpot-SWT_2022-06.zip
          mv $GITHUB_WORKSPACE/ummisco.gama.product/target/products/Gama1.7-macosx.cocoa.x86_64_withJDK.zip $GITHUB_WORKSPACE/jdk17-HotSpot-SWT_2022-06/MacOS-jdk17-HotSpot-SWT_2022-06.zip
          ls -lh $GITHUB_WORKSPACE/jdk17-HotSpot-SWT_2022-06

      - uses: "marvinpinto/action-automatic-releases@latest"
        env:
          working_directory: $GITHUB_WORKSPACE
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: $GITHUB_WORKSPACE/jdk17-HotSpot-SWT_2022-06/*.zip
